name: faded_image_list
description: It helps developers to show Animated image list faded curve.
version: 0.0.2
homepage: "https://github.com/Rajkumar07793/faded_image_list"
documentation: "https://github.com/Rajkumar07793/faded_image_list/blob/master/README.md"
issue_tracker: https://github.com/Rajkumar07793/faded_image_list/issues
environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: